version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    working_dir: /var/www
    volumes:
      - ../:/var/www

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80
      - 8443:443

  # Redis
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  redis_data:
  dbdata:
